services:
  node:
    build:
      context: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    #expose:
    #  - "8081"
    ports:
      - "3000:3030"

    command: "npm run dev"
